version: "3.8"

name: ww-lang-app

services:
  db:
    image: postgres:15.3-alpine3.18
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ww_lang_app
    ports:
      - 5432:5432
    volumes:
      - ./db-data:/var/lib/postgresql/data

volumes:
  db-data: