version: '3.8'

services:
  # reverse-proxy:
  #   build:
  #     context: ./reverse-proxy
  #     dockerfile: Dockerfile
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   links:
  #     - backend:backend

  # backend:
  #   build:
  #     context: ./
  #     target: runner
  #   volumes:
  #     - .:/app
  #   command: npx next
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     NODE_ENV: development
  #     DATABASE_URL: postgresql://postgres:password@db:5432/lang_app
  #   links:
  #     - db:db

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: lang_app
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: "psql -U postgres -lqt | cut -d \\| -f 1 | grep -qw lang_app" # This check is needed to ensure the lang_app database has been created before Prisma attempts to connect to it
      interval: 250ms
      timeout: 3s
      retries: 40
      start_period: 30s
    ports:
      - "5432:5432"

volumes:
  db-data: