version: "3.8"

name: ww-lang-app

services:
    # Next.JS
    app:
        build: .
        ports:
            - 3000:3000
        depends_on:
            db:
                condition: service_healthy
        links:
            - db:postgres

    # PostgreSQL
    db:
        image: postgres:15.3-alpine3.18
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: ww_lang_app
        ports:
            - 5432:5432
        volumes:
            - ./db-data:/var/lib/postgresql/data
        # Ensure that Postgres is healthy before starting the app as
        # starting the app container triggers a migration
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 5s
            timeout: 5s
            retries: 6

volumes:
    db-data:
